[package]
name = "找不到对象"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-dialog = "0.6.3"

[build-dependencies]
winres = "0.1.12"

[profile.release]
lto = true
panic = 'abort'
opt-level = 's'